# Generated by Django 5.1 on 2024-09-09 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0002_contato'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametrosEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='empresa.empresa')),
            ],
        ),
    ]
