# Generated by Django 5.1 on 2024-09-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0002_parametrosempresa_nome_exibicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametrosempresa',
            name='nome_exibicao',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
