# Generated by Django 5.1 on 2024-11-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0003_alter_parametrosempresa_nome_exibicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrosempresa',
            name='contagem_dias_inspecao_computador',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
