# Generated by Django 5.1 on 2024-08-15 18:20

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_rede', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('ATV', 'Ativo'), ('INT', 'Inativo'), ('PTI', 'Parado TI'), ('MNT', 'Manutenção')], default='ATV', max_length=3)),
                ('modelo', models.CharField(max_length=150)),
                ('serial_number', models.CharField(max_length=150)),
                ('data_cadastro', models.DateTimeField(default=datetime.datetime(2024, 8, 15, 18, 20, 11, 177666, tzinfo=datetime.timezone.utc))),
                ('data_ultima_atualizacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('observacoes', models.TextField(blank=True)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='empresa.setor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_marca', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_software', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tipo_equipamento', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Computador',
            fields=[
                ('equipamento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='equipamentos.equipamento')),
            ],
            bases=('equipamentos.equipamento',),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='equipamentos.marca'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='tipo_equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='equipamentos.tipoequipamento'),
        ),
    ]
