# Generated by Django 5.1 on 2024-09-03 18:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_marca', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SistemaOperacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_sistema_operacional', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_software', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tipo_equipamento', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_rede', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('ATV', 'ATIVO'), ('INT', 'INATIVO'), ('PTI', 'PARADO TI'), ('MNT', 'MANUTENÇÃO')], default='ATV', max_length=3)),
                ('modelo', models.CharField(max_length=150)),
                ('serial_number', models.CharField(max_length=150)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_ultima_atualizacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('observacoes', models.TextField(blank=True)),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='empresa.operador')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='empresa.setor')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='equipamentos.marca')),
                ('tipo_equipamento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='equipamentos.tipoequipamento')),
            ],
        ),
        migrations.CreateModel(
            name='SoftwareComputador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=100)),
                ('nf_software', models.FileField(blank=True, null=True, upload_to='nf_software')),
                ('computador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='equipamentos.equipamento')),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='equipamentos.software')),
            ],
        ),
        migrations.CreateModel(
            name='Computador',
            fields=[
                ('equipamento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='equipamentos.equipamento')),
                ('processador', models.CharField(blank=True, max_length=150, null=True)),
                ('memoria', models.CharField(blank=True, max_length=150, null=True)),
                ('armazenamento', models.CharField(blank=True, max_length=150, null=True)),
                ('tipo_armazenamento', models.CharField(blank=True, choices=[('HD', 'HD'), ('SSD', 'SSD'), ('SSD M2', 'SSD M2'), ('CARTÃO SD', 'CARTÃO SD')], default='SSD', max_length=50, null=True)),
                ('so_serial_vbs', models.CharField(blank=True, max_length=150, null=True)),
                ('so_serial_cmd', models.CharField(blank=True, max_length=150, null=True)),
                ('nf_computador', models.FileField(blank=True, null=True, upload_to='nf_computador')),
                ('nf_sistema_operacional', models.FileField(blank=True, null=True, upload_to='nf_sistema_operacional')),
                ('sistema_operacional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='equipamentos.sistemaoperacional')),
            ],
            bases=('equipamentos.equipamento',),
        ),
    ]
