# Generated by Django 5.1 on 2024-08-15 19:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicençaSoftware',
            fields=[
                ('software_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='equipamentos.software')),
                ('serial', models.CharField(max_length=100)),
                ('nf_software', models.FileField(blank=True, null=True, upload_to='nf_software')),
            ],
            bases=('equipamentos.software',),
        ),
        migrations.CreateModel(
            name='SistemaOperacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_sistema_operacional', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='computador',
            name='armazenamento',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='computador',
            name='memoria',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='computador',
            name='nf_computador',
            field=models.FileField(blank=True, null=True, upload_to='nf_computador'),
        ),
        migrations.AddField(
            model_name='computador',
            name='nf_sistema_operacional',
            field=models.FileField(blank=True, null=True, upload_to='nf_sistema_operacional'),
        ),
        migrations.AddField(
            model_name='computador',
            name='processador',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='computador',
            name='so_serial_cmd',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='computador',
            name='so_serial_vbs',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='computador',
            name='tipo_armazenamento',
            field=models.CharField(blank=True, choices=[('HD', 'HD'), ('SSD', 'SSD'), ('SSD M2', 'SSD M2'), ('CARTÃO SD', 'CARTÃO SD')], default='SSD', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='data_cadastro',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 15, 19, 12, 19, 431078, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='status',
            field=models.CharField(choices=[('ATV', 'ATIVO'), ('INT', 'INATIVO'), ('PTI', 'PARADO TI'), ('MNT', 'MANUTENÇÃO')], default='ATV', max_length=3),
        ),
        migrations.AddField(
            model_name='computador',
            name='software',
            field=models.ManyToManyField(blank=True, null=True, to='equipamentos.licençasoftware'),
        ),
        migrations.AddField(
            model_name='computador',
            name='sistema_operacional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='equipamentos.sistemaoperacional'),
        ),
    ]
