# Generated by Django 5.1 on 2024-08-15 19:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0002_licençasoftware_sistemaoperacional_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LicençaSoftware',
            new_name='LicencaSoftware',
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='data_cadastro',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 15, 19, 13, 48, 456176, tzinfo=datetime.timezone.utc)),
        ),
    ]
