# Generated by Django 5.1 on 2024-09-16 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0003_alter_softwarecomputador_serial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computador',
            old_name='numero_nota_fiscal_sistem_operacional',
            new_name='numero_nota_fiscal_sistema_operacional',
        ),
    ]
