# Generated by Django 5.1 on 2024-08-21 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0004_alter_equipamento_data_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='data_cadastro',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 21, 17, 16, 53, 346878, tzinfo=datetime.timezone.utc)),
        ),
    ]
