# Generated by Django 5.1 on 2024-09-26 16:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0004_rename_numero_nota_fiscal_sistem_operacional_computador_numero_nota_fiscal_sistema_operacional'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='proxima_verificacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
