# Generated by Django 5.1 on 2024-10-18 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0005_equipamento_proxima_verificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computador',
            name='sistema_operacional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sistema_operacional', to='equipamentos.sistemaoperacional'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='marca', to='equipamentos.marca'),
        ),
        migrations.AlterField(
            model_name='softwarecomputador',
            name='software',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='software', to='equipamentos.software'),
        ),
    ]
