# Generated by Django 5.1 on 2024-08-26 16:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0005_alter_equipamento_data_cadastro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computador',
            name='software',
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='data_cadastro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='SoftwareComputador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=100)),
                ('nf_software', models.FileField(blank=True, null=True, upload_to='nf_software')),
                ('computador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='equipamentos.equipamento')),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='equipamentos.software')),
            ],
        ),
        migrations.DeleteModel(
            name='LicencaSoftware',
        ),
    ]
