# Generated by Django 5.1 on 2024-10-29 00:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0006_alter_computador_sistema_operacional_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspecaoComputador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inspecao', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.CharField(max_length=150)),
                ('arquivo_computador', models.FileField(blank=True, null=True, upload_to='arquivo_computador')),
                ('check_antivirus', models.BooleanField(default=False)),
                ('check_so', models.BooleanField(default=False)),
                ('check_softwares', models.BooleanField(default=False)),
                ('uso_armazenamento', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True)),
                ('computador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='equipamentos.computador')),
            ],
        ),
    ]
