# Generated by Django 5.1 on 2024-10-29 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0007_inspecaocomputador'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspecaocomputador',
            name='dados_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
