# Generated by Django 5.1 on 2024-09-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(default=1, max_length=255, verbose_name='Título'),
            preserve_default=False,
        ),
    ]
