# Generated by Django 5.1 on 2024-09-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.CharField(max_length=255, verbose_name='Tags'),
        ),
    ]
