# Generated by Django 5.1 on 2024-08-15 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_usuario', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('ATV', 'Ativo'), ('INT', 'Inativo'), ('AFT', 'Afastado')], default='ATV', max_length=3)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='empresa.setor')),
            ],
        ),
    ]
