# Generated by Django 5.1 on 2024-09-03 18:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
        ('equipamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OcorrenciaComputador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo_ocorrencia', models.CharField(choices=[('1', 'INATIVAR COMPUTADOR'), ('2', 'TROCAR OPERADOR DE COMPUTADOR'), ('3', 'RECOLHER COMPUTADOR PARA T.I.'), ('4', 'ATUALIZAR SISTEMA OPERACIONAL'), ('5', 'ATUALIZAR SOFTWARE')], max_length=1)),
                ('observacoes', models.TextField(blank=True)),
                ('computador', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='equipamentos.computador')),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='empresa.operador')),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='empresa.setor')),
            ],
        ),
        migrations.CreateModel(
            name='OcorrenciaOperador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo_ocorrencia', models.CharField(choices=[('1', 'INATIVAR OPERADOR'), ('2', 'TROCAR OPERADOR DE SETOR')], max_length=1)),
                ('observacoes', models.TextField(blank=True)),
                ('operador', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='empresa.operador')),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='empresa.setor')),
            ],
        ),
    ]
