# Generated by Django 5.1 on 2024-08-27 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0002_alter_setor_empresa'),
        ('usuarios', '0002_usuario_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='OcorrenciaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ocorrencia', models.CharField(choices=[('1', 'INATIVAR USUÁRIO'), ('2', 'TROCAR USUÁRIO DE SETOR')], max_length=1)),
                ('observacao', models.TextField(blank=True)),
                ('setor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='empresa.setor')),
                ('usuario', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuario')),
            ],
        ),
    ]
