# Generated by Django 5.1 on 2024-08-28 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ocorrenciausuario',
            old_name='observacao',
            new_name='observacoes',
        ),
    ]
