# Generated by Django 5.1 on 2024-08-28 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_alter_setor_empresa'),
        ('ocorrencias', '0002_rename_observacao_ocorrenciausuario_observacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrenciausuario',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='empresa.setor'),
        ),
    ]
