# Generated by Django 5.1 on 2024-12-04 20:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0002_remove_ocorrenciacomputador_operador_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlaInterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicial', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_final', models.DateTimeField(default=django.utils.timezone.now)),
                ('ocorrido', models.TextField(blank=True)),
                ('solucao', models.TextField(blank=True)),
            ],
        ),
    ]
