# Generated by Django 5.1 on 2024-12-05 11:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0003_slainterno'),
    ]

    operations = [
        migrations.AddField(
            model_name='slainterno',
            name='hora_final',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='slainterno',
            name='hora_inicial',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
