# Generated by Django 5.1 on 2024-09-02 20:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_alter_setor_empresa'),
        ('equipamentos', '0006_remove_computador_software_and_more'),
        ('ocorrencias', '0004_ocorrenciausuario_data'),
        ('usuarios', '0002_usuario_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='OcorrenciaComputador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo_ocorrencia', models.CharField(choices=[('1', 'INATIVAR COMPUTADOR'), ('2', 'TROCAR COMPUTADOR DE USUARIO'), ('3', 'RECOLHER COMPUTADOR PARA T.I.'), ('4', 'ATUALIZAR SISTEMA OPERACIONAL'), ('5', 'ATUALIZAR SOFTWARE')], max_length=1)),
                ('observacoes', models.TextField(blank=True)),
                ('computador', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='equipamentos.computador')),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='empresa.setor')),
                ('usuario', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuario')),
            ],
        ),
    ]
