# Generated by Django 5.1 on 2024-09-02 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0005_ocorrenciacomputador'),
        ('usuarios', '0002_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrenciacomputador',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuario'),
        ),
    ]
