# Generated by Django 5.1 on 2024-12-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0005_alter_slainterno_data_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slainterno',
            name='data_final',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='slainterno',
            name='data_inicial',
            field=models.DateField(),
        ),
    ]
