# Generated by Django 5.1 on 2024-09-09 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_contato', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(choices=[('ATV', 'Ativo'), ('INT', 'Inativo')], default='ATV', max_length=3)),
                ('observacoes', models.TextField(blank=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='empresa.empresa')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='empresa.setor')),
            ],
        ),
    ]
