# Generated by Django 5.1 on 2024-09-09 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_contato'),
    ]

    operations = [
        migrations.AddField(
            model_name='operador',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='empresa.empresa'),
            preserve_default=False,
        ),
    ]
