# Generated by Django 5.1 on 2024-09-11 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_operador_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
    ]
