# Generated by Django 5.1 on 2024-09-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_empresa_observacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='telefone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
